

SECRET_KEY= '67vt167)^0&2h11^a#c@o@-2tcl3)v-(8rysuo=%+5(#q4i7cg'

import jwt

def decode_bearer_token(bearer_token):
    try:
        # Extract the token from the "Authorization" header
        token = bearer_token.split(" ")[1]
        # Replace "YOUR_SECRET_KEY" with the actual secret key used to sign the token
        decoded_token = jwt.decode(token, SECRET_KEY, algorithms=["HS256"])
        return decoded_token
    except jwt.ExpiredSignatureError:
        raise Exception("Token has expired")
    except jwt.InvalidTokenError:
        raise Exception("Invalid token")
    except Exception as e:
        raise Exception("Error decoding token: " + str(e))



# Example usage
bearer_token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IllMV1ZHT0k4Q1NNVjZERVdHSElSN05KUC1XWVM0OExfOFFCR0FUWDQiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJjUXhKdlhuUmovMm1IREVPV1FWOVpRPT0iLCJuYW1lIjoiY3hhZlFvazVkNHF3UGNwdm5ZZTRkZz09Iiwicm9sZSI6IkNBIiwidXNlcm5hbWUiOiJmazJ6dUdudVEvbEoyQnkrUEx2TlRnPT0iLCJhZGRyZXNzIjoiMDlxaUdtNThaR3d3U3VWK1lCcTlZRnFjSXFCVTBqQzNET2pjOVhNOWw1VTB6ZnJ4TWJmcysya0lJZzFCMmQwTUtGaUxveW13WnhweHhDSUNKU3puS0VKMjRkVVV0VkF1TW8zUi9DUTdQd1g0cGNMcncyaHNPR0dTTWV2Mk12VnkiLCJsb2NhbGl0eSI6IjBxNFVXVlBzUFJGZXJESlYrSzdYdGc9PSIsInBlcm1pc3Npb25zIjoiY3RtIHNjIHVjIHJhcyBydWwgcmN3YyByY2NzIHJ1YSByZnMgdWxzdCB1ZnIgZGNvbmYgcnAgcmx1dSBybHUgdGQgY2EgbWQgc2Mgem0gY3AgZXRtIHNtYyBsY21zIGN0bSBjbSB1bSBmcSBhcSBvcHIgaWFxZCBseWNvIGljYXBwIHJsIGNyciBhY3RjZmcgdWxyIHVubCBlX2NmIHNtc19jIHJjYSIsInN1YnNpZGlhcnkiOiItIiwidGhlbWUiOiJ3aGl0ZSIsImxvZ29uYW1lIjoiYXNzZXRzXFxpbWdcXG5pc21cXDYzODI0OTU1MzY0NjU5NTYyME5JU01Mb2dvLnBuZyIsImxvZ29uYW1lZGFyayI6ImFzc2V0c1xcaW1nXFx0YXRhbW90b3JzXFw2MzgyMDM0MzkzNzQ1OTg0NTgyMTB4NTVfZGFyay5wbmciLCJpc2luc3RpdHV0ZSI6IkZhbHNlIiwic3RhdHVzY29kZSI6Ii0iLCJzdGF0dXNjb2RlbWVzc2FnZSI6Ii0iLCJpb3MiOiItIiwibGRhcCI6IjAiLCJleHRfdXNlciI6IjAiLCJmY210b2tlbiI6Ii0iLCJ0b2tlbl91c2FnZSI6ImFjY2Vzc190b2tlbiIsImp0aSI6IjY3YzVmNjNiLWJlNjctNGZlMy04ZGJjLWQyZTFlYmFiMGU2YyIsImF1ZCI6WyJtYXN0ZXJzLWFwaSIsImxvZ2dpbmctYXBpIiwiY29uZmlndXJhdGlvbi1hcGkiLCJ1c2Vycy1hcGkiLCJjb3Vyc2UtYXBpIiwiYXNzZXNzbWVudF9hcGkiLCJiaWxsaW5nX2FwaSIsImNlcnRpZmljYXRpb25fYXBpIiwiY2hhdGJvdF9hcGkiLCJjb21wZXRlbmN5X2FwaSIsImNvbmZpZ3VyYXRpb25fYXBpIiwiZGVncmVlZF9hcGkiLCJmZWVkYmFja19hcGkiLCJnYWRnZXRfYXBpIiwibG9nZ2luZ19hcGkiLCJub3RpZmljYXRpb25fYXBpIiwicmVwb3J0X2FwaSIsInN1cnZleV9hcGkiLCJ6b29tX2FwaSJdLCJuYmYiOjE2ODk3Njc0NjcsImV4cCI6MTY4OTc4MTg2NywiaWF0IjoxNjg5NzY3NDY3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjEwMDEwLyJ9.LXT93_EshDbW_pt7MHM2DL8t9QAM4w0tvJGD38ZR7es8kY4sOU_bKVj6nuuVLXRsr5Mkfrmw2oedp5d58GrzyD4PmsrveQpX4f100O0bJTHAJnmP5ZCIidCzGmkPZC4VMD_zdzR8eakdljuGUzAJrf1Z9ZzFEWyF7_U4ruIOtIrvXei4hBhnYCxPwRcNSQO6CBjHRZA_VNSnN2EJTdCtMFuABYtFGaogaSUJB5LSQBNKx0p4CXKABQAvYs7z4v14DVpaCuXxYA7F-kAC_P7w2rmaAZj3cYRWhYPrYMJG91cPJYwRlkTrE-oZaAsX4JDUhhK53WdWo5vZ3RDH-Fh90g"

try:
    payload = decode_bearer_token(bearer_token)
    print(payload)
except Exception as e:
    print("Error:", str(e))
